server:
  port: 8761

app:
  id: springboot-apollo
apollo:
  meta: http://47.101.150.220:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

logging:
  level:
    com:
      frankcooper:
        controller: debug
