logging:
  config: classpath:logback.xml


server:
  port: 8888


jasypt:
  encryptor:
    password: dataworks
    algorithm: PBEWithMD5AndDES
    bean: encryptorBean


spring:
  application:
    name: data-studio-server
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: process
    passoword: ENC(xxxx)
    driver-class-name: com.mysql.cj.jdbc.Driver