#rabbitmq config
spring:
  rabbitmq:
    host: 47.101.150.220
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 2000